---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graph-visualizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graph-visualizer
  template:
    metadata:
      labels:
        app: graph-visualizer
    spec:
      containers:
        - name: frontend
          image: ghcr.io/jgchen716/graph-visualizer/frontend:v0
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: graph-visualizer
  ports:
    - port: 3000
