---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graph-visualizer-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graph-visualizer-backend
  template:
    metadata:
      labels:
        app: graph-visualizer-backend
    spec:
      containers:
        - name: server
          image: ghcr.io/jgchen716/graph-visualizer/server:v0
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: graph-visualizer-backend
  ports:
    - port: 3001
